pipeline {
  agent {
    docker {
        image '35.239.224.138:8765/agent:4'
        registryUrl 'http://35.239.224.138:8765'
        registryCredentialsId '0dea7b0a-81ed-4cbc-8da5-40323c29eae7'
        args '--privileged -v /var/run/docker.sock:/var/run/docker.sock'
    }
  }
  
  stages {
      
    stage('git clone') {
      steps {
            dir('tmp') {
                git 'https://github.com/chazovam/jenkins_test.git'
            }
        }
    }
    
    stage('build and push') {
      steps {
          dir('tmp') {
            sh 'docker build -t boxfuse .'
            sh 'docker tag boxfuse 35.239.224.138:8765/boxfuse'
            sh 'docker push 35.239.224.138:8765/boxfuse'
          }
        }
    }
    
    stage ('deploy') {
      steps {
          sshagent(credentials : ['server-creds']) {
            sh 'ssh -tt -o StrictHostKeyChecking=no root@34.123.250.38 docker run -d -p 8080:8080 35.239.224.138:8765/boxfuse:latest'
          }
        }
    }
  }
}