---
# tasks file for prod
  - name: Ensure group "tomcat" added
    group:
      name: tomcat

  - name: Ensure user "tomcat" added
    user:
      name: tomcat
      group: tomcat
      home: /usr/local/tomcat
      createhome: no

  - name: Ensure tomcat package is unarchived
    unarchive:
      src: https://downloads.apache.org/tomcat/tomcat-9/v9.0.40/bin/apache-tomcat-9.0.40.tar.gz
      dest: /opt/
      owner: tomcat
      group: tomcat
      remote_src: yes

  - name: Ensure Tomcat symbolic link is created
    file:
      src: /opt/apache-tomcat-9.0.40
      path: /usr/local/tomcat
      state: link

  - name: Ensure Tomcat service file is present
    template:
      src: tomcat.service
      dest: /etc/systemd/system/tomcat.service
    notify: start tomcat service