pipeline {
  agent {
    docker {
        image 'chazovams/agent:latest'
        registryCredentialsId 'docker-hub-creds'
        args '--privileged -v /var/run/docker.sock:/var/run/docker.sock'
    }
  }

  environment {
        AWS_ACCESS_KEY_ID     = credentials('jenkins-aws-secret-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('jenkins-aws-secret-access-key')
        DOCKER_HUB_LOGIN      = credentials('docker-hub-login')
        DOCKER_HUB_PASSWORD   = credentials('docker-hub-password')
  }
  
  stages {
      
    stage('git clone configs') {
      steps {
            dir('tmp') {
                git 'https://github.com/chazovam/devops.git'
            }
        }
    }

    stage('TF environment prepare') {
      steps {
          dir('tmp/final_exam/env') {
            sh 'terraform init'
            sh 'terraform plan -out tfplan'
            sh 'terraform apply -input=false tfplan'
          }
        }
    }
    
    stage('ansible apply server config') {
      steps {
          dir('tmp/final_exam/env') {
            sh 'ansible-playbook -i hosts playbook.yaml'
          }
        }
    }
  }
}