---
- name: build app
  hosts: builder
  become: true
  gather_facts: false
  vars:
    docker_hub_login: "{{ lookup('env','DOCKER_HUB_LOGIN') }}"
    docker_hub_password: "{{ lookup('env','DOCKER_HUB_PASSWORD') }}"

  tasks:
    - name: Ensure basic packages are present
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io
        - git

    - name: Ensure local repository is present
      git:
        repo: 'https://github.com/chazovam/jenkins_test.git'
        dest: /tmp/jenkins_test

    - name: Ensure DockerHub logged into
      community.general.docker_login:
        username: "{{ docker_hub_login }}"
        password: "{{ docker_hub_password }}"

    - name: Ensure image tagged and pushed to docker hub
      docker_image:
        name: chazovams/web
        repository: chazovams/web
        tag: 2
        push: yes
        source: build
        build:
          path: /tmp/jenkins_test/.


- name: run app
  hosts: web
  become: true
  gather_facts: false
  vars:
    docker_hub_login: "{{ lookup('env','DOCKER_HUB_LOGIN') }}"
    docker_hub_password: "{{ lookup('env','DOCKER_HUB_PASSWORD') }}"

  tasks:
    - name: Ensure basic packages are present
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io

    - name: Ensure DockerHub logged into
      community.general.docker_login:
        username: "{{ docker_hub_login }}"
        password: "{{ docker_hub_password }}"

    - name: Ensure application container started
      docker_container:
        name: web
        image: chazovams/web:2
        state: started
        pull: yes
        ports:
        - "8080:8080"